### ISSUE TITLE
Allow customization of icons used for expand and collapse

### ISSUE THREAD

**Issue by rsivan** [vaadin/vaadin-details-flow#21] opened 2019-03-06 02:59 UTC
This is a copy of https://github.com/vaadin/vaadin-details/issues/10 for Vaadin-Flow: allow customization of icons used for expand and collapse.

**Comment by web-padawan** [comment] 2019-03-06 09:01
Let me close this as duplicate of vaadin/vaadin-details#10 and continue the discussion there.

**Closed by web-padawan** 2019-03-06 09:01 UTC
